# Generated by Django 5.2.3 on 2026-07-02 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='active_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='paused_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='total_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Ready', 'Ready'), ('Discovery', 'Discovery'), ('Enumeration', 'Enumeration'), ('Analysis', 'Analysis'), ('Validation', 'Validation'), ('Reporting', 'Reporting'), ('Review', 'Review'), ('Complete', 'Complete'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50),
        ),
        migrations.CreateModel(
            name='AssessmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='engagements.assessment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentWorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.CharField(blank=True, max_length=255, null=True)),
                ('run_id', models.CharField(blank=True, max_length=255, null=True)),
                ('current_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('asset_count', models.PositiveIntegerField(default=0)),
                ('finding_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_state', to='engagements.assessment')),
            ],
        ),
    ]
