# Generated by Django 5.2.3 on 2026-07-02 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_assessment_active_duration_and_more'),
        ('scanEngine', '0016_scanworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='preferred_engine',
            field=models.ForeignKey(blank=True, help_text='Override engine; defaults to assessment-type default engine if unset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='scanEngine.enginetype'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='retention_days',
            field=models.IntegerField(choices=[(90, '90 Days'), (180, '180 Days'), (365, '1 Year'), (0, 'Forever')], default=365, help_text='How long evidence for this assessment is retained before archiving.'),
        ),
    ]
