# Generated by Django 5.2.3 on 2026-07-05 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('engagements', '0003_add_preferred_engine_retention_to_assessment'),
        ('startScan', '0059_vulnerability_validation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Ready', 'Ready'), ('Discovery', 'Discovery'), ('Enumeration', 'Enumeration'), ('Analysis', 'Analysis'), ('Correlation', 'Correlation'), ('Validation', 'Validation'), ('GraphSync', 'GraphSync'), ('Reporting', 'Reporting'), ('Review', 'Review'), ('Complete', 'Complete'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('asset_type', models.CharField(choices=[('VPN Gateway', 'VPN Gateway'), ('Remote Access Protocol', 'Remote Access Protocol'), ('Identity & SSO', 'Identity & SSO'), ('Database', 'Database'), ('Admin Portal', 'Admin Portal'), ('CI/CD & Automation', 'CI/CD & Automation'), ('Container / Orchestration', 'Container / Orchestration'), ('Source Code Repository', 'Source Code Repository'), ('Cloud Storage', 'Cloud Storage'), ('Email Server', 'Email Server'), ('File Sharing', 'File Sharing'), ('Message Queue', 'Message Queue'), ('API Endpoint', 'API Endpoint'), ('Staging / Dev', 'Staging / Dev'), ('WAF / Edge', 'WAF / Edge'), ('VoIP / Communication', 'VoIP / Communication'), ('Web Application', 'Web Application'), ('Application', 'Application'), ('Unclassified Asset', 'Unclassified Asset')], default='Unclassified Asset', max_length=64)),
                ('canonical_identifier', models.CharField(db_index=True, max_length=1024)),
                ('canonical_key_hash', models.CharField(db_index=True, max_length=64)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_assets', to='engagements.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='AssetSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_tool', models.CharField(choices=[('httpx', 'httpx'), ('nuclei', 'nuclei'), ('katana', 'katana'), ('screenshot', 'screenshot'), ('ffuf', 'ffuf'), ('port_scan', 'port_scan'), ('exposure_engine', 'exposure_engine'), ('subdomain_enum', 'subdomain_enum'), ('other', 'other')], max_length=32)),
                ('source_object_id', models.PositiveIntegerField()),
                ('observed_at', models.DateTimeField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='engagements.asset')),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('source_scan_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_sources', to='startScan.scanhistory')),
            ],
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['assessment', 'asset_type'], name='engagements_assessm_232bac_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['assessment', '-risk_score'], name='engagements_assessm_0cb1d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('assessment', 'canonical_key_hash')},
        ),
        migrations.AddIndex(
            model_name='assetsource',
            index=models.Index(fields=['asset', 'source_tool'], name='engagements_asset_i_1239d6_idx'),
        ),
        migrations.AddIndex(
            model_name='assetsource',
            index=models.Index(fields=['source_scan_history'], name='engagements_source__a873a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetsource',
            unique_together={('asset', 'source_content_type', 'source_object_id')},
        ),
    ]
