# Generated by Django 5.2.3 on 2026-06-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0044_epssfeeddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='scan_status',
            field=models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=-1),
        ),
        migrations.AlterField(
            model_name='scanreport',
            name='status',
            field=models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=-1),
        ),
    ]
