# Generated by Django 5.2.3 on 2026-06-19 20:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0046_exposure_vulnerability_exposure_exposureevidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
