# Generated by Django 5.2.3 on 2026-06-20 09:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0047_alter_exposure_type'),
        ('targetApp', '0011_domain_manual_subdomains'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateIntelligence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=1000)),
                ('port', models.IntegerField(default=443)),
                ('subject_cn', models.CharField(blank=True, max_length=500, null=True)),
                ('subject_an', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('issuer_cn', models.CharField(blank=True, max_length=500, null=True)),
                ('issuer_org', models.CharField(blank=True, max_length=500, null=True)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('tls_version', models.CharField(blank=True, max_length=20, null=True)),
                ('cipher', models.CharField(blank=True, max_length=300, null=True)),
                ('fingerprint_sha256', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('self_signed', models.BooleanField(default=False)),
                ('mismatched', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('has_weak_cipher', models.BooleanField(default=False)),
                ('trust_chain', models.JSONField(blank=True, default=list)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('scan_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_intel', to='startScan.scanhistory')),
                ('subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='startScan.subdomain')),
                ('target_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('fingerprint_sha256__isnull', False)), fields=('target_domain', 'fingerprint_sha256'), name='unique_cert_per_domain')],
            },
        ),
    ]
