# Generated by Django 5.2.3 on 2026-06-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0048_add_certificate_intelligence'),
        ('targetApp', '0011_domain_manual_subdomains'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityInfraDiscovery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('host', models.CharField(max_length=1000)),
                ('infra_type', models.CharField(choices=[('adfs', 'ADFS'), ('owa', 'Outlook Web Access'), ('exchange', 'Exchange'), ('ldap', 'LDAP'), ('sso', 'SSO Portal'), ('saml_idp', 'SAML Identity Provider'), ('vpn_portal', 'VPN Portal'), ('ntlm_endpoint', 'NTLM Endpoint'), ('generic_auth_portal', 'Generic Auth Portal')], default='generic_auth_portal', max_length=50)),
                ('detection_method', models.CharField(choices=[('url_pattern', 'URL Pattern'), ('title_keyword', 'Page Title Keyword'), ('header_analysis', 'HTTP Header Analysis'), ('combined', 'Multiple Signals')], default='url_pattern', max_length=50)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('is_externally_accessible', models.BooleanField(default=True)),
                ('additional_signals', models.JSONField(blank=True, default=dict)),
                ('scan_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_infra', to='startScan.scanhistory')),
                ('subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_infra', to='startScan.subdomain')),
                ('target_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
            ],
            options={
                'unique_together': {('scan_history', 'host', 'infra_type')},
            },
        ),
    ]
