# Generated by Django 5.2.3 on 2026-06-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0049_add_identity_infra_discovery'),
        ('targetApp', '0011_domain_manual_subdomains'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIIntelligenceProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_url', models.URLField(max_length=2000)),
                ('api_type', models.CharField(choices=[('rest', 'REST'), ('graphql', 'GraphQL'), ('soap', 'SOAP'), ('generic', 'Generic')], default='rest', max_length=20)),
                ('endpoint_count', models.IntegerField(default=0)),
                ('requires_auth', models.BooleanField(default=False)),
                ('auth_scheme', models.CharField(blank=True, max_length=100, null=True)),
                ('parameters_sample', models.JSONField(blank=True, default=list)),
                ('graphql_schema_snippet', models.TextField(blank=True, null=True)),
                ('raw_endpoints', models.JSONField(blank=True, default=list)),
                ('scan_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_intel', to='startScan.scanhistory')),
                ('subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_intel', to='startScan.subdomain')),
                ('target_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
            ],
            options={
                'unique_together': {('scan_history', 'base_url', 'api_type')},
            },
        ),
    ]
