# Generated by Django 5.2.3 on 2026-06-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0050_add_api_intelligence_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateintelligence',
            name='flag_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateintelligence',
            name='flag_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exposure',
            name='status_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='identityinfradiscovery',
            name='confirmed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='identityinfradiscovery',
            name='dismiss_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identityinfradiscovery',
            name='dismissed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='impactassessment',
            name='dismiss_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impactassessment',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('verified', 'Verified'), ('accepted', 'Accepted'), ('false_positive', 'False Positive'), ('remediated', 'Remediated'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
    ]
