# Generated by Django 5.2.3 on 2026-06-22 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0051_mobile_api_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBreach',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.CharField(max_length=255)),
                ('breach_name', models.CharField(max_length=255)),
                ('breach_date', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('compromised_data', models.JSONField(blank=True, default=list)),
                ('discovered_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.email')),
                ('scan_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
            ],
            options={
                'verbose_name_plural': 'Email Breaches',
                'ordering': ['-discovered_date'],
            },
        ),
    ]
