# Generated by Django 5.2.3 on 2026-06-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0052_emailbreach'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('hunter', 'Hunter.io'), ('harvester', 'theHarvester'), ('phonebook', 'Phonebook.cz'), ('pattern', 'Pattern Inference'), ('crawled', 'Crawled URLs')], default='hunter', max_length=50),
        ),
    ]
