# Generated by Django 5.2.3 on 2026-06-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0054_add_dns_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
