# Generated by Django 5.2.3 on 2026-06-29 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        ('startScan', '0055_alter_dnsrecord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_histories', to='engagements.assessment'),
        ),
        migrations.AddField(
            model_name='subscan',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_scans', to='engagements.assessment'),
        ),
    ]
