# Generated by Django 5.2.3 on 2026-07-06 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0057_vulnerability_affected_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbreach',
            name='source',
            field=models.CharField(default='hibp', max_length=50),
        ),
        migrations.CreateModel(
            name='CredResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=255)),
                ('tool_name', models.CharField(max_length=50)),
                ('ms_tenant', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=500, null=True)),
                ('exposure_type', models.CharField(blank=True, max_length=100, null=True)),
                ('has_password', models.BooleanField(blank=True, null=True)),
                ('remote_ngc', models.BooleanField(blank=True, null=True)),
                ('has_fido', models.BooleanField(blank=True, null=True)),
                ('has_cert_auth', models.BooleanField(blank=True, null=True)),
                ('domain_type', models.CharField(blank=True, max_length=50, null=True)),
                ('account_exists', models.BooleanField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('discovered_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='startScan.email')),
                ('scan_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
            ],
            options={
                'verbose_name_plural': 'Credential Results',
                'ordering': ['-discovered_date'],
            },
        ),
    ]
