# Generated by Django 5.2.3 on 2026-07-21 10:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0060_merge_emailbreach_credresult_validation'),
        ('targetApp', '0011_domain_manual_subdomains'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_scan_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='Ordered list of ScanHistory IDs included in this report', size=None)),
                ('included_sections', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text='Section keys included in this report', size=None)),
                ('status', models.IntegerField(choices=[(0, 'Failed'), (1, 'Running'), (2, 'Complete')], default=1)),
                ('report_type', models.CharField(default='full', max_length=50)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='target_reports/')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_reports', to='targetApp.domain')),
            ],
            options={
                'verbose_name_plural': 'Target Reports',
            },
        ),
    ]
