# Generated by Django 5.2.3 on 2026-07-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0061_add_targetreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetreport',
            name='report_type',
            field=models.CharField(default='full', help_text='Reserved for future report variants (e.g. vulnerability-only).', max_length=50),
        ),
    ]
