# Generated by Django 5.2.3 on 2026-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_linkedincredentials_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'GitHub API Key',
            },
        ),
        migrations.CreateModel(
            name='LeakSearchAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LeakSearch API Key',
            },
        ),
    ]
