# Generated by Django 5.2.3 on 2026-09-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_merge_acunetix_submission_llmsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityTrailsAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
            ],
        ),
    ]
