# Generated by keygen.py - commit this file, NEVER commit signing.key
TRUSTED_PUBLIC_KEYS: list[bytes] = [
    b'\xc1,Z/\x1e\xdc\x8a\x99\xd5b6KCB\x8b\xb1\xfd\x94+"+\x97\x0es\xa7g-\xae\xa2\x19\xda\x94',
]
