import os
import shutil
import threading
import time
import zipfile
import yaml
import json
import subprocess
from datetime import datetime
from django.conf import settings
from django.utils.text import slugify
from django.db import transaction
from django.core.management import call_command
import requests
from django.core.cache import cache
import logging
try:
    from .plugin_keys import TRUSTED_PUBLIC_KEYS
except (ImportError, SyntaxError):
    # plugin_keys.py is generated by keygen.py, so it can arrive malformed.
    # A SyntaxError there is not an ImportError and used to escape this guard,
    # and since PluginsConfig.ready() imports this module the whole Django app
    # registry failed to load rather than just the plugin signature check.
    TRUSTED_PUBLIC_KEYS: list[bytes] = []
from .models import Plugin

logger = logging.getLogger(__name__)

class MarketplaceManager:
    MARKETPLACE_YAML_URL = "https://raw.githubusercontent.com/whiterabb17/r3ngine-plugins/master/plugins.yaml"
    CACHE_KEY = "marketplace_plugins"
    CACHE_TIMEOUT = 3600  # 1 hour

    @classmethod
    def get_available_plugins(cls, force_refresh=False):
        if not force_refresh:
            cached_data = cache.get(cls.CACHE_KEY)
            if cached_data:
                return cached_data

        try:
            import packaging.version
            response = requests.get(cls.MARKETPLACE_YAML_URL, timeout=10)
            if response.status_code == 200:
                data = yaml.safe_load(response.text)
                plugins = data.get('marketplace', [])
                
                # Fetch all installed plugins to compare versions
                installed_plugins = {p.slug: p for p in Plugin.objects.all()}
                
                for plugin in plugins:
                    slug = plugin.get('slug')
                    if slug in installed_plugins:
                        plugin['is_installed'] = True
                        installed_ver = installed_plugins[slug].version
                        plugin['installed_version'] = installed_ver
                        
                        try:
                            m_ver = packaging.version.parse(str(plugin.get('version', '0.0.0')))
                            i_ver = packaging.version.parse(str(installed_ver))
                            plugin['update_available'] = m_ver > i_ver
                        except Exception as e:
                            logger.error(f"Version parsing error for plugin {slug}: {e}")
                            plugin['update_available'] = False
                    else:
                        plugin['is_installed'] = False
                        plugin['installed_version'] = None
                        plugin['update_available'] = False
                
                cache.set(cls.CACHE_KEY, plugins, cls.CACHE_TIMEOUT)
                return plugins
            else:
                raise Exception(f"Marketplace unreachable: {response.status_code}")
        except Exception as e:
            logger.error(f"Failed to fetch marketplace: {str(e)}")
            return []

    @classmethod
    def download_plugin(cls, slug):
        download_url = f"https://raw.githubusercontent.com/whiterabb17/r3ngine-plugins/master/{slug}/{slug}.r3n"
        temp_zip_path = os.path.join(PluginManager.BASE_PLUGINS_DIR, f"download_{slug}.r3n")
        PluginManager.ensure_dirs()
        
        response = requests.get(download_url, stream=True, timeout=30)
        if response.status_code == 200:
            try:
                with open(temp_zip_path, 'wb') as f:
                    for chunk in response.iter_content(chunk_size=8192):
                        f.write(chunk)
                return temp_zip_path
            except Exception as e:
                if os.path.exists(temp_zip_path):
                    os.remove(temp_zip_path)
                raise e
        else:
            raise Exception(f"Failed to download plugin {slug}: {response.status_code}")

class PluginManager:
    """Handles file operations for plugins: extraction, validation, and deletion."""
    
    BASE_PLUGINS_DIR = os.path.join(settings.BASE_DIR, 'plugins_data')
    BACKUPS_DIR = os.path.join(BASE_PLUGINS_DIR, 'backups')
    
    @classmethod
    def ensure_dirs(cls):
        os.makedirs(cls.BASE_PLUGINS_DIR, exist_ok=True)
        os.makedirs(cls.BACKUPS_DIR, exist_ok=True)
        
    @classmethod
    def extract_plugin(cls, zip_path):
        """Extracts a plugin zip and returns the path to the actual plugin content (flattening root dir if needed)."""
        temp_dir = os.path.join(cls.BASE_PLUGINS_DIR, 'temp_' + datetime.now().strftime('%Y%m%d%H%M%S'))
        os.makedirs(temp_dir, exist_ok=True)

        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            # Validate all member paths before extraction to prevent Zip Slip attacks.
            safe_root = os.path.realpath(temp_dir) + os.sep
            for member in zip_ref.infolist():
                dest = os.path.realpath(os.path.join(temp_dir, member.filename))
                if not dest.startswith(safe_root):
                    raise ValueError(f"Unsafe path in plugin archive: {member.filename}")
            zip_ref.extractall(temp_dir)
            
        # If there's only one directory and no files in the root, move everything up
        items = os.listdir(temp_dir)
        if len(items) == 1 and os.path.isdir(os.path.join(temp_dir, items[0])):
            root_item = os.path.join(temp_dir, items[0])
            # Move all contents of the root_item to temp_dir
            for sub_item in os.listdir(root_item):
                shutil.move(os.path.join(root_item, sub_item), temp_dir)
            # Remove the now-empty root_item
            os.rmdir(root_item)
            
        return temp_dir

    @classmethod
    def validate_manifest(cls, plugin_dir):
        """Validates the manifest.yaml file."""
        manifest_path = os.path.join(plugin_dir, 'manifest.yaml')
        if not os.path.exists(manifest_path):
            raise Exception("Manifest.yaml not found in plugin archive.")
            
        with open(manifest_path, 'r') as f:
            manifest = yaml.safe_load(f)
            
        required_fields = ['name', 'version', 'runtime']
        for field in required_fields:
            if field not in manifest:
                raise Exception(f"Missing required field '{field}' in manifest.yaml")
                
        # Validate runtime keys.
        # Valid anchor values: any real scan task name (e.g. "subdomain_discovery")
        # or "standalone" for plugins that operate independently of the main scan pipeline.
        runtime = manifest.get('runtime', {})
        if not any(k in runtime for k in ['run after', 'run before']):
            raise Exception("Manifest must specify 'run after' or 'run before' in runtime section.")
            
        return manifest

    @classmethod
    def delete_plugin_files(cls, plugin_slug):
        """Deletes all files associated with a plugin."""
        final_dir = os.path.join(cls.BASE_PLUGINS_DIR, plugin_slug)
        if os.path.exists(final_dir):
            shutil.rmtree(final_dir)

    @classmethod
    def verify_r3n(cls, r3n_path):
        """Open a .r3n file, verify content hash and optional Ed25519 signature.

        Returns (plugin_zip_bytes, meta_dict, verification_result) where
        verification_result is one of: 'official' | 'signed_unknown' | 'unsigned'.
        Raises ValueError on hash mismatch or invalid signature.
        """
        import hashlib
        import base64
        import io as _io
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
        from cryptography.exceptions import InvalidSignature

        with open(r3n_path, 'rb') as f:
            r3n_bytes = f.read()

        with zipfile.ZipFile(_io.BytesIO(r3n_bytes), 'r') as r3n_zip:
            names = r3n_zip.namelist()
            if 'r3n_manifest.json' not in names:
                raise ValueError("Not a valid .r3n file: missing r3n_manifest.json")
            if 'plugin.zip' not in names:
                raise ValueError("Not a valid .r3n file: missing plugin.zip")
            meta = json.loads(r3n_zip.read('r3n_manifest.json'))
            plugin_zip_bytes = r3n_zip.read('plugin.zip')

        actual_hash = hashlib.sha256(plugin_zip_bytes).hexdigest()
        if actual_hash != meta.get('content_hash'):
            raise ValueError("Content hash mismatch — archive may be tampered")

        raw_sig = meta.get('signature')
        raw_pub = meta.get('public_key')

        if not raw_sig or not raw_pub:
            return plugin_zip_bytes, meta, 'unsigned'

        try:
            pub_key_bytes = base64.b64decode(raw_pub)
            sig_bytes = base64.b64decode(raw_sig)
            pub_key = Ed25519PublicKey.from_public_bytes(pub_key_bytes)
            pub_key.verify(sig_bytes, actual_hash.encode())
        except InvalidSignature:
            raise ValueError("Invalid signature — archive may be tampered")
        except Exception as e:
            raise ValueError(f"Signature verification error: {e}")

        if pub_key_bytes in TRUSTED_PUBLIC_KEYS:
            return plugin_zip_bytes, meta, 'official'
        return plugin_zip_bytes, meta, 'signed_unknown'

class AtomicInstaller:
    """Handles the safe installation of plugins with backup and rollback."""

    STEPS = [
        ('upload',      'Saving plugin archive'),
        ('extract',     'Extracting archive'),
        ('verify',      'Verifying integrity'),
        ('validate',    'Validating manifest'),
        ('backup',      'Creating database backup'),
        ('register',    'Registering plugin'),
        ('migrations',  'Running database migrations'),
        ('assets',      'Installing UI assets & fixtures'),
        ('complete',    'Installation complete'),
    ]

    @staticmethod
    def _emit(install_id: str, key: str, step_status: str, message: str = ''):
        if not install_id:
            return
        label = next((lbl for k, lbl in AtomicInstaller.STEPS if k == key), key)
        data = cache.get(f'plugin:install:{install_id}') or {'steps': [], 'status': 'running', 'plugin_name': None}
        steps = data['steps']
        for s in steps:
            if s['key'] == key:
                s['status'] = step_status
                s['message'] = message
                break
        else:
            steps.append({'key': key, 'label': label, 'status': step_status, 'message': message})
        data['steps'] = steps
        cache.set(f'plugin:install:{install_id}', data, timeout=300)

    @classmethod
    def backup_db(cls, plugin_slug):
        """Creates a database backup before installation."""
        timestamp = datetime.now().strftime('%Y%m%d%H%M%S')
        backup_file = os.path.join(PluginManager.BACKUPS_DIR, f"pre_{plugin_slug}_{timestamp}.sql")
        
        db_config = settings.DATABASES['default']
        cmd = [
            'pg_dump',
            '-h', str(db_config.get('HOST', 'db')),
            '-p', str(db_config.get('PORT', '5432')),
            '-U', str(db_config.get('USER')),
            '-d', str(db_config.get('NAME')),
            '-f', str(backup_file)
        ]
        
        try:
            env = os.environ.copy()
            if db_config.get('PASSWORD'):
                env['PGPASSWORD'] = str(db_config.get('PASSWORD'))
            
            logger.info(f"Creating database backup: {backup_file}")
            subprocess.run(cmd, check=True, env=env, capture_output=True, text=True)
            return backup_file
        except subprocess.CalledProcessError as e:
            logger.error(f"Database backup failed: {e.stderr}")
            raise Exception(f"Database backup failed: {e.stderr}")
        except Exception as e:
            logger.error(f"Unexpected error during backup: {str(e)}")
            raise e

    @classmethod
    def rollback_db(cls, backup_file):
        """Restores the database from a backup."""
        if not os.path.exists(backup_file):
            return
            
        db_config = settings.DATABASES['default']
        cmd = [
            'psql',
            '-h', str(db_config.get('HOST', 'db')),
            '-p', str(db_config.get('PORT', '5432')),
            '-U', str(db_config.get('USER')),
            '-d', str(db_config.get('NAME')),
            '-f', str(backup_file)
        ]
        
        try:
            env = os.environ.copy()
            if db_config.get('PASSWORD'):
                env['PGPASSWORD'] = str(db_config.get('PASSWORD'))
            
            logger.info(f"Rolling back database from: {backup_file}")
            subprocess.run(cmd, check=True, env=env, capture_output=True, text=True)
        except subprocess.CalledProcessError as e:
            logger.error(f"CRITICAL: Rollback failed! {e.stderr}")
        except Exception as e:
            logger.error(f"CRITICAL: Rollback failed! {str(e)}")

    @classmethod
    def install(cls, zip_path: str, install_id: str = None):
        """Performs the full atomic installation."""
        PluginManager.ensure_dirs()
        temp_dir = None
        backup_db_file = None
        backup_fs_dir = None
        plugin_slug = None
        final_dir = None
        inner_zip_path = None
        verification_result = 'legacy'
        r3n_meta: dict = {}

        try:
            cls._emit(install_id, 'extract', 'in_progress')

            if zip_path.endswith('.r3n'):
                cls._emit(install_id, 'verify', 'in_progress')
                plugin_zip_bytes, r3n_meta, verification_result = PluginManager.verify_r3n(zip_path)
                inner_zip_path = zip_path.replace('.r3n', '_inner.zip')
                with open(inner_zip_path, 'wb') as _f:
                    _f.write(plugin_zip_bytes)
                actual_zip = inner_zip_path
                _trust_msg = {
                    'official':       'Verified — official r3ngine plugin',
                    'signed_unknown': 'Signed by unverified publisher',
                    'unsigned':       'Unsigned plugin',
                }.get(verification_result, '')
                cls._emit(install_id, 'verify', 'completed', _trust_msg)
            else:
                actual_zip = zip_path
                verification_result = 'legacy'
                cls._emit(install_id, 'verify', 'completed', 'Legacy .zip — unverified')

            temp_dir = PluginManager.extract_plugin(actual_zip)
            cls._emit(install_id, 'extract', 'completed')

            cls._emit(install_id, 'validate', 'in_progress')
            manifest = PluginManager.validate_manifest(temp_dir)
            plugin_name = manifest['name']
            plugin_slug = slugify(plugin_name).replace('-', '_')
            # Update plugin_name in cache once we know it
            if install_id:
                data = cache.get(f'plugin:install:{install_id}') or {}
                data['plugin_name'] = plugin_name
                cache.set(f'plugin:install:{install_id}', data, timeout=300)
            cls._emit(install_id, 'validate', 'completed')

            # 1. Backup DB
            cls._emit(install_id, 'backup', 'in_progress')
            backup_db_file = cls.backup_db(plugin_slug)
            cls._emit(install_id, 'backup', 'completed')

            # 2. Prepare FS Backups
            final_dir = os.path.join(PluginManager.BASE_PLUGINS_DIR, plugin_slug)

            if os.path.exists(final_dir):
                backup_fs_dir = f"{final_dir}_bak_{int(time.time())}"
                shutil.copytree(final_dir, backup_fs_dir)

            cls._emit(install_id, 'register', 'in_progress')
            with transaction.atomic():
                # 3. Register in DB
                runtime = manifest.get('runtime', {})
                anchor = runtime.get('run after') or runtime.get('run before')
                position = 'AFTER' if 'run after' in runtime else 'BEFORE'

                plugin, created = Plugin.objects.update_or_create(
                    slug=plugin_slug,
                    defaults={
                        'name': plugin_name,
                        'version': manifest['version'],
                        'description': manifest.get('description', ''),
                        'manifest': manifest,
                        'anchor_step': anchor,
                        'runtime_position': position,
                        'author': r3n_meta.get('author', manifest.get('author', '')),
                        'trust_level': verification_result,
                        'icon_path': manifest.get('icon', ''),
                    }
                )
                cls._emit(install_id, 'register', 'completed')

                # 4. Finalize file placement
                if os.path.exists(final_dir):
                    shutil.rmtree(final_dir)
                shutil.move(temp_dir, final_dir)
                
            # --- End of transaction.atomic() block ---
            # Migration and fixture steps are performed OUTSIDE the long transaction so that
            # we do not trigger 'server closed the connection unexpectedly' errors caused by
            # PostgreSQL dropping idle connections inside a long transaction (idle-in-transaction timeout).
            from django.db import connection as _db_conn
            _db_conn.close()

            # 5. Ingest Engine Fixtures and Run Migrations
            # Run dynamic migrations if the plugin has models
            backend_dir = os.path.join(final_dir, 'backend')
            if os.path.exists(os.path.join(backend_dir, 'models.py')):
                # Ensure package directories have __init__.py files present
                for d in [final_dir, backend_dir]:
                    init_f = os.path.join(d, '__init__.py')
                    if not os.path.exists(init_f):
                        try:
                            with open(init_f, 'w') as f:
                                pass
                        except Exception:
                            pass

                app_label = f"{plugin_slug}_backend"
                logger.info(f"Running migrations for plugin app: {app_label}")
                cls._emit(install_id, 'migrations', 'in_progress')
                try:
                    import sys
                    # Run makemigrations in a clean subprocess to auto-load the new app config
                    makemigrate_res = subprocess.run(
                        [sys.executable, "manage.py", "makemigrations", app_label],
                        cwd=settings.BASE_DIR,
                        capture_output=True,
                        text=True,
                        check=True
                    )
                    logger.info(f"Subprocess makemigrations stdout: {makemigrate_res.stdout}")
                    
                    # Run migrate in a clean subprocess
                    migrate_res = subprocess.run(
                        [sys.executable, "manage.py", "migrate", app_label],
                        cwd=settings.BASE_DIR,
                        capture_output=True,
                        text=True,
                        check=True
                    )
                    logger.info(f"Subprocess migrate stdout: {migrate_res.stdout}")
                    logger.info(f"Successfully migrated plugin: {plugin_slug}")
                    cls._emit(install_id, 'migrations', 'completed')
                except subprocess.CalledProcessError as e:
                    logger.error(f"Failed to run migrations for {plugin_slug} (exit {e.returncode}):\nStdout: {e.stdout}\nStderr: {e.stderr}")
                    raise Exception(f"Migration subprocess failed for {app_label}: {e.stderr or e.stdout}")
                except Exception as e:
                    logger.error(f"Unexpected error running migrations for {plugin_slug}: {str(e)}")
                    raise e
            else:
                # Plugin has no models — migrations not needed
                cls._emit(install_id, 'migrations', 'skipped')

            cls._emit(install_id, 'assets', 'in_progress')
            from scanEngine.models import EngineType
            for file in os.listdir(final_dir):
                if file.endswith('_engine.yaml'):
                    fixture_path = os.path.join(final_dir, file)
                    logger.info(f"Ingesting engine fixture: {fixture_path}")
                    try:
                        with open(fixture_path, 'r') as f:
                            fixture_data = yaml.safe_load(f)
                            if isinstance(fixture_data, list):
                                for item in fixture_data:
                                    if item.get('model') == 'scanEngine.enginetype':
                                        fields = item.get('fields', {})
                                        name = fields.get('engine_name')
                                        if name:
                                            obj, created = EngineType.objects.update_or_create(
                                                engine_name=name,
                                                defaults=fields
                                            )
                                            logger.info(f"{'Created' if created else 'Updated'} engine: {name}")
                                        else:
                                            logger.warning(f"Engine fixture item missing engine_name: {item}")
                                    else:
                                        # Fallback for other models (e.g. Wordlist, etc.)
                                        call_command('loaddata', fixture_path, format='yaml')
                                        logger.info(f"Fallback loaddata used for: {file}")
                            else:
                                logger.error(f"Invalid fixture format in {file}")
                    except Exception as e:
                        logger.error(f"CRITICAL: Failed to ingest engine fixture {file}: {str(e)}")

            # 6. Parse tools.yaml — save in its own short transaction with a fresh connection.
            tools_path = os.path.join(final_dir, 'tools.yaml')
            if os.path.exists(tools_path):
                try:
                    from django.db import connection as _db_conn
                    _db_conn.ensure_connection()
                    with open(tools_path, 'r') as f:
                        tools_config = yaml.safe_load(f)

                    with transaction.atomic():
                        # Re-fetch the plugin record to get a live ORM instance.
                        _plugin = Plugin.objects.get(slug=plugin_slug)
                        _plugin.tools_config = tools_config
                        _plugin.save(update_fields=['tools_config'])

                    # Invalidate per-tool verification cache so the orchestrator
                    # re-installs tools on its next startup rather than skipping them.
                    for _tool in tools_config.get('tools', []):
                        _tool_name = _tool.get('name')
                        if _tool_name:
                            cache.delete(f"plugin_{plugin_slug}_tool_{_tool_name}_verified")

                    # Trigger orchestrator restart via Redis so it picks up the new plugin
                    # and installs any required tools in its own container on startup.
                    def _restart_orchestrator():
                        try:
                            import redis as _redis
                            from django.conf import settings as _settings
                            rdb = _redis.StrictRedis(
                                host=_settings.REDIS_HOST,
                                port=_settings.REDIS_PORT,
                                password=_settings.REDIS_PASSWORD,
                                db=0,
                            )
                            rdb.publish('orchestrator_control', 'restart')
                            logger.info(f"[{plugin_slug}] Orchestrator restart triggered for tool installation.")
                        except Exception as _e:
                            logger.error(f"[{plugin_slug}] Failed to trigger orchestrator restart: {_e}")

                    threading.Thread(target=_restart_orchestrator, daemon=True).start()
                except Exception as e:
                    logger.error(f"Failed to parse tools.yaml for {plugin_slug}: {str(e)}")

            # Trigger a graceful delayed restart of the web container so it picks up
            # the new plugin API URLs without instantly severing this HTTP response.
            def _restart_web_container():
                import time
                time.sleep(2)  # Give the current JSON response time to reach the client
                try:
                    import docker
                    client = docker.from_env()
                    web_container = client.containers.get('r3ngine-web-1')
                    logger.info(f"[{plugin_slug}] Restarting web container to load new API routes.")
                    web_container.restart()
                except Exception as _e:
                    logger.error(f"[{plugin_slug}] Failed to restart web container: {_e}")

            threading.Thread(target=_restart_web_container, daemon=True).start()

            # Set needs_restart to True in cache
            cache.set(f"plugin_{plugin_slug}_needs_restart", True, timeout=None)

            # 7. Promote ui/dist/ contents into ui/ so PluginUIView can serve them.
            # PluginUIView serves directly from plugins_data/{slug}/ui/, so built
            # assets must live there (not in a dist/ subdirectory).
            ui_dist_src = os.path.join(final_dir, 'ui', 'dist')
            if os.path.exists(ui_dist_src):
                ui_dir = os.path.join(final_dir, 'ui')
                for item in os.listdir(ui_dist_src):
                    src_item = os.path.join(ui_dist_src, item)
                    dst_item = os.path.join(ui_dir, item)
                    if os.path.exists(dst_item):
                        if os.path.isdir(dst_item):
                            shutil.rmtree(dst_item)
                        else:
                            os.remove(dst_item)
                    shutil.move(src_item, dst_item)
                shutil.rmtree(ui_dist_src)

            cls._emit(install_id, 'assets', 'completed')

            # 8. Cleanup backups on success
            if backup_fs_dir and os.path.exists(backup_fs_dir):
                shutil.rmtree(backup_fs_dir)
            if backup_db_file and os.path.exists(backup_db_file):
                os.remove(backup_db_file)
            if inner_zip_path and os.path.exists(inner_zip_path):
                os.remove(inner_zip_path)

            cls._emit(install_id, 'complete', 'completed')
            if install_id:
                data = cache.get(f'plugin:install:{install_id}') or {}
                data['status'] = 'success'
                _warning_messages = {
                    'unsigned': 'This plugin is unsigned. Install at your own risk.',
                    'signed_unknown': 'This plugin is signed by an unrecognized publisher.',
                    'legacy': 'This is a legacy .zip plugin with no integrity verification.',
                }
                if verification_result in _warning_messages:
                    data['warning'] = _warning_messages[verification_result]
                cache.set(f'plugin:install:{install_id}', data, timeout=300)

            return Plugin.objects.get(slug=plugin_slug)
                
        except Exception as e:
            logger.error(f"Installation failed for {plugin_slug}: {str(e)}")
            # Mark the current in-progress step as failed and update overall status
            if install_id:
                data = cache.get(f'plugin:install:{install_id}') or {'steps': [], 'status': 'running'}
                for s in data.get('steps', []):
                    if s['status'] == 'in_progress':
                        s['status'] = 'failed'
                        s['message'] = str(e)
                data['status'] = 'failed'
                data['error'] = str(e)
                cache.set(f'plugin:install:{install_id}', data, timeout=300)
            # Rollback DB
            if backup_db_file:
                cls.rollback_db(backup_db_file)
            
            # Rollback FS
            if backup_fs_dir and os.path.exists(backup_fs_dir):
                if os.path.exists(final_dir):
                    shutil.rmtree(final_dir)
                shutil.move(backup_fs_dir, final_dir)
            else:
                if final_dir and os.path.exists(final_dir):
                    shutil.rmtree(final_dir)

            if temp_dir and os.path.exists(temp_dir):
                shutil.rmtree(temp_dir)
            if inner_zip_path and os.path.exists(inner_zip_path):
                os.remove(inner_zip_path)
            raise e
