# Generated by Django 5.2.3 on 2026-09-19 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='McpApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=16)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='McpInstanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_mode', models.CharField(choices=[('stdio', 'stdio'), ('http', 'http'), ('both', 'both')], default='stdio', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='McpSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transport', models.CharField(choices=[('stdio', 'stdio'), ('http', 'http')], max_length=8)),
                ('client_name', models.CharField(blank=True, default='', max_length=200)),
                ('client_version', models.CharField(blank=True, default='', max_length=100)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mcp.mcpapikey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='McpAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tool_name', models.CharField(blank=True, default='', max_length=120)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=300)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('truncated', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='mcp.mcpapikey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_audit_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='mcp.mcpsession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'created_at'], name='mcp_mcpaudi_session_266cbd_idx'), models.Index(fields=['user', 'created_at'], name='mcp_mcpaudi_user_id_3172da_idx')],
            },
        ),
    ]
