# Generated by Django 5.2.3 on 2026-09-19 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='McpAgent',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('provider', models.CharField(blank=True, default='', max_length=80)),
                ('ide', models.CharField(blank=True, default='', max_length=80)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('os_name', models.CharField(blank=True, default='', max_length=80)),
                ('hostname', models.CharField(blank=True, default='', max_length=200)),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_agents_banned', to=settings.AUTH_USER_MODEL)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='mcp.mcpapikey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='McpAgentBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(blank=True, default='', max_length=80)),
                ('ide', models.CharField(blank=True, default='', max_length=80)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('hostname', models.CharField(blank=True, default='', max_length=200)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_agent_ban_actions', to=settings.AUTH_USER_MODEL)),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_bans', to='mcp.mcpapikey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_agent_bans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mcpsession',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='mcp.mcpagent'),
        ),
        migrations.AddField(
            model_name='mcpsession',
            name='agent_username',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mcpsession',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='mcpsession',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mcpsession',
            name='ide',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='mcpsession',
            name='os_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='mcpsession',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddIndex(
            model_name='mcpagent',
            index=models.Index(fields=['key', 'last_seen_at'], name='mcp_mcpagen_key_id_7c1a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpagent',
            index=models.Index(fields=['user', 'last_seen_at'], name='mcp_mcpagen_user_id_2a91f4_idx'),
        ),
    ]
