# Generated by Django 5.2.3 on 2026-09-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0004_followup_plan_index_names'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mcpagent',
            new_name='mcp_mcpagen_key_id_ff8590_idx',
            old_name='mcp_mcpagen_key_id_7c1a0e_idx',
        ),
        migrations.RenameIndex(
            model_name='mcpagent',
            new_name='mcp_mcpagen_user_id_265321_idx',
            old_name='mcp_mcpagen_user_id_2a91f4_idx',
        ),
    ]
