# Generated by Django 5.2.3 on 2026-09-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0006_attack_path_proposal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attackpathproposal',
            new_name='mcp_attackp_project_e79d3c_idx',
            old_name='mcp_attackp_project_idx',
        ),
        migrations.RenameIndex(
            model_name='attackpathproposal',
            new_name='mcp_attackp_scan_id_0b945e_idx',
            old_name='mcp_attackp_scan_id_idx',
        ),
        migrations.RenameIndex(
            model_name='attackpathproposal',
            new_name='mcp_attackp_target__d4ad0a_idx',
            old_name='mcp_attackp_path_id_idx',
        ),
    ]
