import re

PATH_TOOLS = (
    (re.compile(r'^/api/mcp/sessions/?$'), {'POST': 'session_open', 'GET': 'session_list'}),
    (re.compile(r'^/api/mcp/sessions/[^/]+/end/?$'), {'POST': 'session_end'}),
    (re.compile(r'^/api/mcp/projects/?$'), {'GET': 'r3ngine_list_projects'}),
    (re.compile(r'^/api/mcp/targets/\d+/detail/?$'), {'GET': 'r3ngine_get_target_detail'}),
    (re.compile(r'^/api/mcp/targets/\d+/?$'), {'GET': 'r3ngine_get_target'}),
    (re.compile(r'^/api/mcp/targets/?$'), {'GET': 'r3ngine_list_targets'}),
    (re.compile(r'^/api/mcp/scans/start/?$'), {'POST': 'r3ngine_start_scan'}),
    (re.compile(r'^/api/mcp/scans/pause/?$'), {'POST': 'r3ngine_pause_scan'}),
    (re.compile(r'^/api/mcp/scans/resume/?$'), {'POST': 'r3ngine_resume_scan'}),
    (re.compile(r'^/api/mcp/scans/stop/?$'), {'POST': 'r3ngine_stop_scan'}),
    (re.compile(r'^/api/mcp/scans/\d+/export-ai/?$'), {'GET': 'r3ngine_export_scan_for_ai'}),
    (re.compile(r'^/api/mcp/scans/\d+/detail/?$'), {'GET': 'r3ngine_get_scan_detail'}),
    (re.compile(r'^/api/mcp/scans/\d+/?$'), {'GET': 'r3ngine_get_scan'}),
    (re.compile(r'^/api/mcp/scans/?$'), {'GET': 'r3ngine_list_scans'}),
    (re.compile(r'^/api/mcp/scan-status/?$'), {'GET': 'r3ngine_get_scan_status'}),
    (re.compile(r'^/api/mcp/subscans/start/?$'), {'POST': 'r3ngine_start_subscan'}),
    (re.compile(r'^/api/mcp/subscans/\d+/detail/?$'), {'GET': 'r3ngine_get_subscan_detail'}),
    (re.compile(r'^/api/mcp/subscans/?$'), {'GET': 'r3ngine_list_subscans'}),
    (re.compile(r'^/api/mcp/subdomains/\d+/detail/?$'), {'GET': 'r3ngine_get_subdomain_detail'}),
    (re.compile(r'^/api/mcp/subdomains/?$'), {'GET': 'r3ngine_list_subdomains'}),
    (re.compile(r'^/api/mcp/endpoints/\d+/detail/?$'), {'GET': 'r3ngine_get_endpoint_detail'}),
    (re.compile(r'^/api/mcp/endpoints/?$'), {'GET': 'r3ngine_list_endpoints'}),
    (re.compile(r'^/api/mcp/vulnerabilities/\d+/analyze/?$'), {'GET': 'r3ngine_analyze_vulnerability'}),
    (re.compile(r'^/api/mcp/vulnerabilities/\d+/enrich/?$'), {'PATCH': 'r3ngine_enrich_vulnerability'}),
    (re.compile(r'^/api/mcp/vulnerabilities/\d+/validation/?$'), {'PATCH': 'r3ngine_validate_vulnerability'}),
    (re.compile(r'^/api/mcp/vulnerabilities/\d+/detail/?$'), {'GET': 'r3ngine_get_vulnerability_detail'}),
    (re.compile(r'^/api/mcp/vulnerabilities/?$'), {'GET': 'r3ngine_list_vulnerabilities'}),
    (re.compile(r'^/api/mcp/exposures/\d+/detail/?$'), {'GET': 'r3ngine_get_exposure_detail'}),
    (re.compile(r'^/api/mcp/exposures/?$'), {'GET': 'r3ngine_list_exposures'}),
    (re.compile(r'^/api/mcp/emails/?$'), {'GET': 'r3ngine_list_emails'}),
    (re.compile(r'^/api/mcp/employees/?$'), {'GET': 'r3ngine_list_employees'}),
    (re.compile(r'^/api/mcp/osint-staging/verify/?$'), {'POST': 'r3ngine_verify_osint_staging'}),
    (re.compile(r'^/api/mcp/osint-staging/?$'), {'GET': 'r3ngine_list_osint_staging'}),
    (re.compile(r'^/api/mcp/search/?$'), {'GET': 'r3ngine_search'}),
    (re.compile(r'^/api/mcp/dashboard/?$'), {'GET': 'r3ngine_get_dashboard'}),
    (re.compile(r'^/api/mcp/attack-paths/[^/]+/enrich/?$'), {'PATCH': 'r3ngine_enrich_attack_path'}),
    (re.compile(r'^/api/mcp/attack-paths/?$'), {'GET': 'r3ngine_get_attack_paths'}),
    (re.compile(r'^/api/mcp/engines/\d+/?$'), {'GET': 'r3ngine_get_engine_detail'}),
    (re.compile(r'^/api/mcp/engines/?$'), {'GET': 'r3ngine_list_engines'}),
    (re.compile(r'^/api/mcp/capabilities/?$'), {'GET': 'r3ngine_list_capabilities'}),
    (re.compile(r'^/api/mcp/health/?$'), {'GET': 'r3ngine_get_system_health'}),
    (re.compile(r'^/api/mcp/tasks/retry/?$'), {'POST': 'r3ngine_retry_task'}),
    (re.compile(r'^/api/mcp/tools/run/?$'), {'POST': 'r3ngine_run_tool'}),
    (re.compile(r'^/api/mcp/tools/[^/]+/args/?$'), {'GET': 'r3ngine_get_tool_args'}),
    (re.compile(r'^/api/mcp/followups/propose/?$'), {'POST': 'r3ngine_propose_followups'}),
    (re.compile(r'^/api/mcp/followups/metrics/?$'), {'GET': 'r3ngine_get_followup_metrics'}),
    (re.compile(r'^/api/mcp/followups/\d+/update/?$'), {'POST': 'r3ngine_update_followups'}),
    (re.compile(r'^/api/mcp/followups/\d+/approve/?$'), {'POST': 'r3ngine_approve_followups'}),
    (re.compile(r'^/api/mcp/followups/\d+/abort/?$'), {'POST': 'r3ngine_abort_followups'}),
    (re.compile(r'^/api/mcp/followups/\d+/retry/?$'), {'POST': 'r3ngine_retry_followups'}),
    (re.compile(r'^/api/mcp/followups/\d+/?$'), {'GET': 'r3ngine_get_followup_plan'}),
    (re.compile(r'^/api/mcp/followups/?$'), {'GET': 'r3ngine_list_followups'}),
    (re.compile(r'^/api/mcp/email-discovery/start/?$'), {'POST': 'r3ngine_start_email_discovery'}),
    (re.compile(r'^/api/mcp/email-discovery/stop/?$'), {'POST': 'r3ngine_stop_email_discovery'}),
    (re.compile(r'^/api/mcp/employee-intel/start/?$'), {'POST': 'r3ngine_start_employee_intel'}),
    (re.compile(r'^/api/mcp/employee-intel/stop/?$'), {'POST': 'r3ngine_stop_employee_intel'}),
    (re.compile(r'^/api/mcp/apme/trigger/?$'), {'POST': 'r3ngine_trigger_apme'}),
    (re.compile(r'^/api/mcp/apme/recalculate/?$'), {'POST': 'r3ngine_recalculate_apme'}),
    (re.compile(r'^/api/mcp/notes/\d+/?$'), {
        'GET': 'r3ngine_get_note',
        'PATCH': 'r3ngine_update_note',
    }),
    (re.compile(r'^/api/mcp/notes/?$'), {
        'GET': 'r3ngine_list_notes',
        'POST': 'r3ngine_create_note',
    }),
    (re.compile(r'^/api/mcp/workflows/start/?$'), {'POST': 'r3ngine_start_workflow'}),
)


def tool_name_for(method: str, path: str) -> str:
    method = method.upper()
    for pattern, methods in PATH_TOOLS:
        if pattern.match(path):
            return methods.get(method, '')
    return ''
