from django.urls import path

from mcp.views.audit import McpAuditListView, McpSessionEventsView
from mcp.views.keys import McpKeyListCreateView, McpKeyRegenerateView, McpKeyRevokeView
from mcp.views.dispatch import (
    McpPauseScanView,
    McpRecalculateApmeView,
    McpResumeScanView,
    McpRetryTaskView,
    McpStartEmailDiscoveryView,
    McpStartEmployeeIntelView,
    McpStartScanView,
    McpStartSubscanView,
    McpStartWorkflowView,
    McpStopEmailDiscoveryView,
    McpStopEmployeeIntelView,
    McpStopScanView,
    McpTriggerApmeView,
)
from mcp.views.detail import (
    McpExportScanForAiView,
    McpGetEndpointDetailView,
    McpGetExposureDetailView,
    McpGetScanDetailView,
    McpGetSubdomainDetailView,
    McpGetSubscanDetailView,
    McpGetTargetDetailView,
    McpGetVulnerabilityDetailView,
)
from mcp.views.validation import (
    McpAnalyzeVulnerabilityView,
    McpEnrichAttackPathView,
    McpEnrichVulnerabilityView,
    McpValidateVulnerabilityView,
)
from mcp.views.notes import McpNoteDetailView, McpNotesListCreateView
from mcp.views.osint_verify import McpVerifyOsintStagingView
from mcp.views.read import (
    McpAttackPathsView,
    McpDashboardView,
    McpGetScanView,
    McpGetTargetView,
    McpHealthView,
    McpListEmailsView,
    McpListEmployeesView,
    McpListEndpointsView,
    McpListEnginesView,
    McpListExposuresView,
    McpListOsintStagingView,
    McpListProjectsView,
    McpListScansView,
    McpListSubdomainsView,
    McpListSubscansView,
    McpListTargetsView,
    McpListVulnerabilitiesView,
    McpScanStatusView,
    McpSearchView,
)
from mcp.views.sessions import (
    McpAgentDeleteView,
    McpSessionEndView,
    McpSessionHeartbeatView,
    McpSessionListCreateView,
    McpSessionRevokeView,
)
from mcp.views.capabilities import (
    McpAbortFollowupsView,
    McpApproveFollowupsView,
    McpFollowupMetricsView,
    McpGetEngineDetailView,
    McpGetFollowupPlanView,
    McpListCapabilitiesView,
    McpListFollowupsView,
    McpProposeFollowupsView,
    McpRetryFollowupsView,
    McpRunToolView,
    McpGetToolArgsView,
    McpUpdateFollowupsView,
)
from mcp.views.settings import McpSettingsView

urlpatterns = [
    path('settings/', McpSettingsView.as_view()),
    path('keys/', McpKeyListCreateView.as_view()),
    path('keys/<int:pk>/regenerate/', McpKeyRegenerateView.as_view()),
    path('keys/<int:pk>/revoke/', McpKeyRevokeView.as_view()),
    path('sessions/', McpSessionListCreateView.as_view()),
    path('sessions/<uuid:pk>/heartbeat/', McpSessionHeartbeatView.as_view()),
    path('sessions/<uuid:pk>/end/', McpSessionEndView.as_view()),
    path('sessions/<uuid:pk>/revoke/', McpSessionRevokeView.as_view()),
    path('sessions/<uuid:pk>/events/', McpSessionEventsView.as_view()),
    path('agents/<str:agent_id>/', McpAgentDeleteView.as_view()),
    path('audit/', McpAuditListView.as_view()),
    path('projects/', McpListProjectsView.as_view()),
    path('targets/<int:pk>/detail/', McpGetTargetDetailView.as_view()),
    path('targets/<int:pk>/', McpGetTargetView.as_view()),
    path('targets/', McpListTargetsView.as_view()),
    path('scans/<int:pk>/export-ai/', McpExportScanForAiView.as_view()),
    path('scans/<int:pk>/detail/', McpGetScanDetailView.as_view()),
    path('scans/<int:pk>/', McpGetScanView.as_view()),
    path('scans/', McpListScansView.as_view()),
    path('scan-status/', McpScanStatusView.as_view()),
    path('subscans/<int:pk>/detail/', McpGetSubscanDetailView.as_view()),
    path('subscans/', McpListSubscansView.as_view()),
    path('subdomains/<int:pk>/detail/', McpGetSubdomainDetailView.as_view()),
    path('subdomains/', McpListSubdomainsView.as_view()),
    path('endpoints/<int:pk>/detail/', McpGetEndpointDetailView.as_view()),
    path('endpoints/', McpListEndpointsView.as_view()),
    path('vulnerabilities/<int:pk>/analyze/', McpAnalyzeVulnerabilityView.as_view()),
    path('vulnerabilities/<int:pk>/enrich/', McpEnrichVulnerabilityView.as_view()),
    path('vulnerabilities/<int:pk>/validation/', McpValidateVulnerabilityView.as_view()),
    path('vulnerabilities/<int:pk>/detail/', McpGetVulnerabilityDetailView.as_view()),
    path('vulnerabilities/', McpListVulnerabilitiesView.as_view()),
    path('exposures/<int:pk>/detail/', McpGetExposureDetailView.as_view()),
    path('exposures/', McpListExposuresView.as_view()),
    path('emails/', McpListEmailsView.as_view()),
    path('employees/', McpListEmployeesView.as_view()),
    path('osint-staging/verify/', McpVerifyOsintStagingView.as_view()),
    path('osint-staging/', McpListOsintStagingView.as_view()),
    path('search/', McpSearchView.as_view()),
    path('dashboard/', McpDashboardView.as_view()),
    path('attack-paths/<str:path_id>/enrich/', McpEnrichAttackPathView.as_view()),
    path('attack-paths/', McpAttackPathsView.as_view()),
    path('engines/<int:pk>/', McpGetEngineDetailView.as_view()),
    path('engines/', McpListEnginesView.as_view()),
    path('capabilities/', McpListCapabilitiesView.as_view()),
    path('health/', McpHealthView.as_view()),
    path('notes/', McpNotesListCreateView.as_view()),
    path('notes/<int:pk>/', McpNoteDetailView.as_view()),
    path('scans/start/', McpStartScanView.as_view()),
    path('scans/pause/', McpPauseScanView.as_view()),
    path('scans/resume/', McpResumeScanView.as_view()),
    path('scans/stop/', McpStopScanView.as_view()),
    path('subscans/start/', McpStartSubscanView.as_view()),
    path('tasks/retry/', McpRetryTaskView.as_view()),
    path('tools/run/', McpRunToolView.as_view()),
    path('tools/<str:tool>/args/', McpGetToolArgsView.as_view()),
    path('followups/', McpListFollowupsView.as_view()),
    path('followups/propose/', McpProposeFollowupsView.as_view()),
    path('followups/metrics/', McpFollowupMetricsView.as_view()),
    path('followups/<int:pk>/', McpGetFollowupPlanView.as_view()),
    path('followups/<int:pk>/update/', McpUpdateFollowupsView.as_view()),
    path('followups/<int:pk>/approve/', McpApproveFollowupsView.as_view()),
    path('followups/<int:pk>/abort/', McpAbortFollowupsView.as_view()),
    path('followups/<int:pk>/retry/', McpRetryFollowupsView.as_view()),
    path('email-discovery/start/', McpStartEmailDiscoveryView.as_view()),
    path('email-discovery/stop/', McpStopEmailDiscoveryView.as_view()),
    path('employee-intel/start/', McpStartEmployeeIntelView.as_view()),
    path('employee-intel/stop/', McpStopEmployeeIntelView.as_view()),
    path('apme/trigger/', McpTriggerApmeView.as_view()),
    path('apme/recalculate/', McpRecalculateApmeView.as_view()),
    path('workflows/start/', McpStartWorkflowView.as_view()),
]
