# Generated by Django 5.2.3 on 2026-07-03 08:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0003_add_preferred_engine_retention_to_assessment'),
        ('startScan', '0056_scanhistory_assessment_subscan_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('evidence_type', models.CharField(choices=[('Screenshot', 'Screenshot'), ('NetworkCapture', 'Network Capture (PCAP/HAR)'), ('RequestResponse', 'HTTP Request/Response'), ('CommandOutput', 'Command Output'), ('Log', 'Log File'), ('Report', 'Report Document'), ('Other', 'Other')], default='Screenshot', max_length=50)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, help_text='Storage key or filesystem path', max_length=2048, null=True)),
                ('file_name', models.CharField(blank=True, max_length=512, null=True)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sha256_hash', models.CharField(blank=True, help_text='SHA-256 hex digest of raw file content for tamper detection', max_length=64, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Archived', 'Archived'), ('Purged', 'Purged')], default='Active', max_length=20)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_evidence', to=settings.AUTH_USER_MODEL)),
                ('scopes', models.ManyToManyField(blank=True, help_text='Scope entries (targets) this evidence is for', related_name='evidence_items', to='engagements.assessmentscope')),
                ('vulnerabilities', models.ManyToManyField(blank=True, help_text='Vulnerabilities / findings this evidence supports', related_name='evidence_items', to='startScan.vulnerability')),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidence Items',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(choices=[('Note', 'Note'), ('Tag', 'Tag'), ('Highlight', 'Highlight')], default='Note', max_length=20)),
                ('content', models.TextField()),
                ('region', models.JSONField(blank=True, help_text='Optional highlighted region descriptor', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_annotations', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='evidence.evidence')),
            ],
            options={
                'verbose_name': 'Evidence Annotation',
                'verbose_name_plural': 'Evidence Annotations',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Archived', 'Archived'), ('Purged', 'Purged')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_collections', to='engagements.assessment')),
                ('scan_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_collections', to='startScan.scanhistory')),
            ],
            options={
                'verbose_name': 'Evidence Collection',
                'verbose_name_plural': 'Evidence Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='evidence.evidencecollection'),
        ),
        migrations.CreateModel(
            name='EvidenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated'), ('Verified', 'Integrity Verified'), ('Downloaded', 'Downloaded'), ('Annotated', 'Annotated'), ('Archived', 'Archived'), ('Purged', 'Purged')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('hash_at_event', models.CharField(blank=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_events', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='evidence.evidence')),
            ],
            options={
                'verbose_name': 'Evidence Event',
                'verbose_name_plural': 'Evidence Events',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_after_days', models.IntegerField(default=365, help_text='Days until archive. 0=never.')),
                ('purge_after_days', models.IntegerField(default=0, help_text='Days after archive to purge. 0=never.')),
                ('purge_files', models.BooleanField(default=False, help_text='Delete actual files on purge?')),
                ('last_enforced_at', models.DateTimeField(blank=True, null=True)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policy', to='evidence.evidencecollection')),
            ],
            options={
                'verbose_name': 'Evidence Retention Policy',
                'verbose_name_plural': 'Evidence Retention Policies',
            },
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['collection', 'status'], name='evidence_ev_collect_74bd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['sha256_hash'], name='evidence_ev_sha256__999c37_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['evidence_type'], name='evidence_ev_evidenc_f1caae_idx'),
        ),
    ]
