# Generated by Django 5.2.3 on 2026-06-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0014_add_scan_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsec',
            name='enable_transparent_proxy_detection',
            field=models.BooleanField(default=False, help_text='Reject proxies that do not change the outbound IP (transparent proxies). Opt-in.'),
        ),
        migrations.AddField(
            model_name='proxy',
            name='proxies_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the stored proxy list was last batch-verified as live.', null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='proxy_ttl_minutes',
            field=models.IntegerField(default=120, help_text='Minutes before the verified proxy list is considered stale (default 120).'),
        ),
    ]
