# Generated by Django 5.2.3 on 2026-06-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0015_proxy_verified_at_opsec_transparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanWorker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('auth_token', models.CharField(max_length=255, unique=True)),
                ('task_queue', models.CharField(max_length=100)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
